# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Bash@3
  displayName: "Downloading required files"
  inputs:
    targetType: 'inline'
    script: 'curl -LJO https://raw.githubusercontent.com/whitesource-ft/xModuleAnalyzer-NET/main/xModuleAnalyzer-NET.ps1 && curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar'
    workingDirectory: $(build.artifactStagingDirectory)

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(build.artifactStagingDirectory)/WebApp.zip'
    destinationFolder: '$(build.artifactStagingDirectory)/.'
    cleanDestinationFolder: false
    overwriteExistingFiles: false

- task: Bash@3
  displayName: "checking what is there"
  inputs:
    targetType: 'inline'
    script: 'ls -la'
    workingDirectory: $(build.artifactStagingDirectory)

- task: PowerShell@2
  displayName: "Hope this works"
  inputs:
     targetType: 'inline'
     script: '.\xModuleAnalyzer-NET.ps1 -d $(Build.SourcesDirectory) -c $(Build.SourcesDirectory)\wss-unified-agent.config -productName AZDO_Scom ‑fsaJarPath wss-unified-agent.jar'
     workingDirectory: $(build.artifactStagingDirectory)

